#Set false if you are not using a permission system
UsePermissions: false
#Allow infinity bows to shoot special arrows without it taking the arrow?
InfinityBowWorks: false
#Can Skeletons shoot arrows? --> Define % in SkeletonArrows.yml!
SkeletonCanShootArrow: true
#Should Skeletons drop special arrows?
SkeletonsDropArrows: true